name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Asciidoctor
      run: |
        sudo apt-get update
        sudo apt-get install -y asciidoctor asciidoctor-pdf

    - name: Convert AsciiDoc files to PDF (English)
      run: |
        asciidoctor-pdf en/*.asciidoc -D output/
        echo "Asciidoctor PDF conversion (English) exit code: $?"

    - name: Convert AsciiDoc files to EPUB (English)
      run: |
        asciidoctor-epub3 en/*.asciidoc -D output/
        echo "Asciidoctor EPUB conversion (English) exit code: $?"

    - name: Convert AsciiDoc files to PDF (Portuguese)
      run: |
        asciidoctor-pdf pt/*.asciidoc -D output/
        echo "Asciidoctor PDF conversion (Portuguese) exit code: $?"

    - name: Convert AsciiDoc files to EPUB (Portuguese)
      run: |
        asciidoctor-epub3 pt/*.asciidoc -D output/
        echo "Asciidoctor EPUB conversion (Portuguese) exit code: $?"

    - name: Convert Additional Docs to PDF
      run: |
        asciidoctor-pdf docs/*.asciidoc -D output/
        echo "Asciidoctor PDF conversion (Additional Docs) exit code: $?"

    - name: Convert Additional Docs to EPUB
      run: |
        asciidoctor-epub3 docs/*.asciidoc -D output/
        echo "Asciidoctor EPUB conversion (Additional Docs) exit code: $?"

    - name: Upload PDF and EPUB
      uses: actions/upload-artifact@v2
      with:
        name: compiled-books
        path: output/
        
    - name: Commit and Push compiled books
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT_3 }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT_3 }}@github.com/${{ github.repository }}
        git add output/*.pdf output/*.epub
        git commit -m 'Add compiled PDF and EPUB books'
        git push origin main
