name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AsciiDoctor
      run: |
        sudo apt-get update
        sudo apt-get install -y asciidoctor
        gem install --user-install asciidoctor-pdf
        gem install --user-install asciidoctor-epub3
      env:
        GEM_HOME: $HOME/.gem
        PATH: $HOME/.gem/bin:$PATH

    - name: Verify AsciiDoctor installation
      run: |
        asciidoctor --version
        asciidoctor-pdf --version
        asciidoctor-epub3 --version
      env:
        GEM_HOME: $HOME/.gem
        PATH: $HOME/.gem/bin:$PATH

    - name: List files in en directory
      run: ls -al en

    - name: Convert AsciiDoc files to PDF (English)
      run: |
        asciidoctor-pdf en/*.adoc -o PDF_en-US_Bitcoin_Technology.pdf
        echo "AsciiDoctor PDF conversion (English) exit code: $?"

    - name: Convert AsciiDoc files to EPUB (English)
      run: |
        asciidoctor-epub3 en/*.adoc -o EPUB_en-US_Bitcoin_Technology.epub
        echo "AsciiDoctor EPUB conversion (English) exit code: $?"

    - name: List generated files
      run: ls -al

    - name: Upload PDF and EPUB
      uses: actions/upload-artifact@v4
      with:
        name: compiled-books
        path: ./

    - name: Commit and Push compiled books
      env:
        ACTIONS_PAT_3: ${{ secrets.ACTIONS_PAT_3 }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT_3 }}@github.com/${{ github.repository }}
        git add PDF_en-US_Bitcoin_Technology.pdf EPUB_en-US_Bitcoin_Technology.epub
        git commit -m 'Add compiled PDF and EPUB books'
        git push origin main
