name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.x

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y asciidoc
        gem install asciidoctor
        gem install asciidoctor-pdf

    - name: Check asciidoctor version
      run: asciidoctor --version

    - name: List files in en directory
      run: ls -al en

    - name: Convert AsciiDoc files to PDF (English)
      run: |
        asciidoctor-pdf en/*.adoc -o PDF_en-US_Bitcoin_Technology.pdf
        echo "AsciiDoctor PDF conversion (English) exit code: $?"

    - name: Convert AsciiDoc files to EPUB (English)
      run: |
        asciidoctor-epub3 en/*.adoc -o EPUB_en-US_Bitcoin_Technology.epub
        echo "AsciiDoctor EPUB conversion (English) exit code: $?"

    - name: List files in pt directory
      run: ls -al pt

    - name: Convert AsciiDoc files to PDF (Portuguese)
      run: |
        asciidoctor-pdf pt/*.adoc -o PDF_pt-BR_Tecnologia_Bitcoin.pdf
        echo "AsciiDoctor PDF conversion (Portuguese) exit code: $?"

    - name: Convert AsciiDoc files to EPUB (Portuguese)
      run: |
        asciidoctor-epub3 pt/*.adoc -o EPUB_pt-BR_Tecnologia_Bitcoin.epub
        echo "AsciiDoctor EPUB conversion (Portuguese) exit code: $?"

    - name: Upload PDF and EPUB
      uses: actions/upload-artifact@v4
      with:
        name: compiled-books
        path: ./

    - name: Commit and Push compiled books
      env:
        ACTIONS_PAT_3: ${{ secrets.ACTIONS_PAT_3 }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}
        git add PDF_en-US_Bitcoin_Technology.pdf EPUB_en-US_Bitcoin_Technology.epub PDF_pt-BR_Tecnologia_Bitcoin.pdf EPUB_pt-BR_Tecnologia_Bitcoin.epub
        git commit -m 'Add compiled PDF and EPUB books'
        git push origin main
