name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic
        pip install pypandoc markdown

    - name: Check pandoc version
      run: pandoc --version

    - name: List files in en directory
      run: ls -al en

    - name: Convert Markdown files to PDF (English)
      run: |
        pandoc en/*.md -o PDF_en-US_Bitcoin_Technology.pdf --pdf-engine=xelatex
        echo "Pandoc PDF conversion (English) exit code: $?"

    - name: Convert Markdown files to EPUB (English)
      run: |
        pandoc en/*.md -o EPUB_en-US_Bitcoin_Technology.epub
        echo "Pandoc EPUB conversion (English) exit code: $?"

    - name: List files in pt directory
      run: ls -al pt

    - name: Convert Markdown files to PDF (Portuguese)
      run: |
        pandoc pt/*.md -o PDF_pt-BR_Tecnologia_Bitcoin.pdf --pdf-engine=xelatex
        echo "Pandoc PDF conversion (Portuguese) exit code: $?"

    - name: Convert Markdown files to EPUB (Portuguese)
      run: |
        pandoc pt/*.md -o EPUB_pt-BR_Tecnologia_Bitcoin.epub
        echo "Pandoc EPUB conversion (Portuguese) exit code: $?"

    - name: Upload PDF and EPUB
      uses: actions/upload-artifact@v4
      with:
        name: compiled-books
        path: ./

    - name: Commit and Push compiled books
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}
        git add PDF_en-US_Bitcoin_Technology.pdf EPUB_en-US_Bitcoin_Technology.epub PDF_pt-BR_Tecnologia_Bitcoin.pdf EPUB_pt-BR_Tecnologia_Bitcoin.epub
        git commit -m 'Add compiled PDF and EPUB books'
        git push origin main
